// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rat
IntegerMatrix rat(NumericVector x, double eps, int maxConv);
RcppExport SEXP fractional_rat(SEXP xSEXP, SEXP epsSEXP, SEXP maxConvSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type maxConv(maxConvSEXP);
    __result = Rcpp::wrap(rat(x, eps, maxConv));
    return __result;
END_RCPP
}
